### ISSUE TITLE
You must be holder of the token to view it

### ISSUE THREAD

**Issue by kevingkday** [CoinClubQuincy/EncryptedNFT-Documents#2]
Isn't it simple to spoof msg.sender and get the encryption key?  Furthermore, what is the purpose of the encryption key if it is a hash of the image hash plus a random key (is this the key used to encrypt the image)?  What would user do with this hash?  If you are just sending the key used to encrypt the image to the recipient then what is the purpose of the contract to begin with, as it seems that anyone can gain access to the encryption key stored in the contract anyway.  Am I missing something?

**Comment by CoinClubQuincy** [comment]
I think you missed the point where this is only plausible on private networks the contract is encrypted on the private net meaning the key isn't visible meaning the token holder would need to release the encryption key from the contract to unlock their file, and this key cant be breached directly unless the token associated is compromised

the fundamental point is you can launch the contract on the the XDC private network (or any other evm private network like Quorum) and you can store the encryption keys (which is generated off chin) of encrypted files (the image scrambling article was an example of storing a key for an encrypted image but the file can literally be any type of file) but the encryption key is in the contract the Hash of the image will be stored in the URI metadata along with the name of the image/images, & url of the IPFS/ bucket storage(cloud) service.

The hash is to confirm that the image/batch of images you decrypted is the image or batch for the Token its to detect fraud so if someone made a similar file and that looked the same to the naked I the Hash will tell you that thats is not the file associated with the token meaning it could be a fraud or at least an incorrect file 

also you cant spoof msg.sender and only the holder of the token can call the contract so theres nothing to spoof anyway 

the encryption key is the generated key to encrypt the file
the hash is a hash of the file to compare to be sure its the correct file

(HASH + initial encryption seed data) = generate encryption key (using any encryption algorithm)

the hash in that adds more entropy to the encryption Key 

[In short, encryption is a two-way function that includes encryption and decryption https://www.ssl2buy.com/wiki/what-is-encryption-and-decryption/  whilst hashing is a one-way function that changes a plain text to a unique digest that is irreversible.
Hashing and encryption are different but also have some similarities.](https://www.ssl2buy.com/wiki/difference-between-hashing-and-encryption#:~:text=The%20difference%20between%20hashing%20and%20encryption&text=In%20short%2C%20encryption%20is%20a,but%20also%20have%20some%20similarities.)


[Yes, msg.sender is secure as elliptic curve cryptography. Ethereum uses the same curve and key size as Bitcoin. Everyone knows msg.sender but only possession of the private key will allow someone to sign a transaction as that msg.sender.](https://ethereum.stackexchange.com/questions/11445/is-mapping-via-msg-sender-as-secure-as-calling-a-function-only-by-the-owner#:~:text=Yes%2C%20msg.,and%20key%20size%20as%20Bitcoin.)
