### ISSUE TITLE
How secure is it?

### ISSUE THREAD

**Issue by fhirfly** [CoinClubQuincy/EncryptedNFT-Documents#3]
Interesting, but if I give someone an NFT that gives them access to my private key, then they can just copy my private key and anyone can decrypt my data.  Usually I encrypt data with my private key and your public key and then you use your private key and my public key to access it.  Once your private key is compromised that's it.  Am I missing something?

**Comment by CoinClubQuincy** [comment]
The point of this NFT is that they are keys on private networks it's simply a token that can unlock data, this data can be MFA time data,encrypted key data,licensing key, whatever. 

This isn't just an NFT you hand around to anyone, its a key to data 

yeah if you want to save your encryption key you can, once accessed or sell the token for someone else to access the keys

but this is a blockchain storage method to access them this could also work as a password storage dapp similar to LastPass or any other means of storing strings of data
